site_name: Robótica Computacional - Insper
theme:
  name: active-handout-theme
  language: pt


markdown_extensions:
  - active-handout-plugins:
      custom_variables:
        data_infra_linux: "TBA"
        data_infra_simulador: "TBA"
        data_infra_turtlebot3: "TBA"
  - toc:
      toc_depth: 0
  - markdown.extensions.admonition
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: "content/"
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - attr_list
  - pymdownx.arithmatex:
      generic: true

plugins:
    - active-handout


nav:
    - index.md
    - Infra:
      - guias-infra/index.md
      - Linux:
        - guias-infra/ssd-linux/index.md
        - guias-infra/ssd-linux/recebi-meu-ssd.md
        - guias-infra/ssd-linux/primeiros-passos.md
        - guias-infra/ssd-linux/terminal-basico.md
        - guias-infra/ssd-linux/git-e-github.md
      - Robô Simulado:
        - guias-infra/simulador/index.md
      - Robô TurtleBot3
        - guias-infra/turtlebot3/index.md
    - Modulos:
      - modulos/visao1
      - modulos/visao2
      - modulos/visao3
      - modulos/visao4
    - Projetos:
      - projeto/index.md
