site_name: Robótica Computacional - Insper
site_url: https://insper.github.io/robotica-computacional/
theme:
  name: active-handout-theme
  locale: pt_BR

extra_css:
    - equipe.css

extra:
  custom_variables:
    data_infra_linux: "25/08"
    data_infra_simulador: "01/09"
    data_infra_turtlebot3: "01/09"
    repo_aps: https://github.com/Insper/robotica-computacional-aps
    repo_aps_git: https://github.com/Insper/robotica-computacional-aps.git
    data_final_APS: 28/03
    data_APS1: 25/08
    data_APS2: 14/09
    data_APS3: 25/09
    data_APS4: 13/11
    avaliacao_CV: 02/10
    data_PF: 04/12
    data_AI: 02/10
    # COlocar links do classroom

markdown_extensions:
  - toc:
      toc_depth: 0
  - markdown.extensions.admonition
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: "content/"
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - attr_list
  - pymdownx.arithmatex:
      generic: true

plugins:
    - active-handout
    - mknotebooks


nav:
    - index.md
    - Infra:
      - guias-infra/index.md
      - Linux:
        - guias-infra/ssd-linux/index.md
        - "Primeiro boot com SSD":
            - guias-infra/ssd-linux/recebi-meu-ssd/index.md
            - guias-infra/ssd-linux/recebi-meu-ssd/windows.md
            - guias-infra/ssd-linux/recebi-meu-ssd/mac-os.md
        - guias-infra/ssd-linux/primeiros-passos/index.md
        - guias-infra/ssd-linux/guia-linux/index.md
        - guias-infra/ssd-linux/git-e-github/index.md
        - guias-infra/ssd-linux/git-e-github/pull_template.md
      - Robô Simulado:
        - guias-infra/robo-simulado/index.md
      - Robô TurtleBot3:
        - guias-infra/turtlebot3/index.md
      - guias-infra/aps.md
      - guias-infra/checagem.md
    - Módulos:
      - modulos/index.md
      - "00 - Introdução":
        - "Sobre o curso": modulos/00-intro/index.md
        - modulos/00-intro/atividade-dia1.md
        - "Para saber mais": modulos/00-intro/recursos-legais.md
      - "01 - Imagens e Matrizes":
        - modulos/01-imagens-e-matrizes/index.md
        - "Atividades":
          - "Leitura de imagens": modulos/01-imagens-e-matrizes/atividade1.ipynb
          - "Percorrendo a imagem": modulos/01-imagens-e-matrizes/atividade2.ipynb
          - "Cookbook de Numpy": modulos/01-imagens-e-matrizes/atividade3.ipynb
          - "Segmentação de imagens por cor": modulos/01-imagens-e-matrizes/atividade4.ipynb
          - "Classes em Python": modulos/01-imagens-e-matrizes/atividade5.ipynb
      - "02 - Modelo de Câmera":
        - modulos/02-modelo-de-camera/index.md
        - "Atividades":
          - "Segmentação usando HSV": modulos/02-modelo-de-camera/atividade1.ipynb
          - "Morfologia Matemática": modulos/02-modelo-de-camera/atividade2.ipynb
          - "Componentes Conexos": modulos/02-modelo-de-camera/atividade3.ipynb
          - "Exemplo de Resolução de Problemas": modulos/02-modelo-de-camera/atividade4.ipynb 
          - "Regressão Linear": modulos/02-modelo-de-camera/atividade5.ipynb 
      - "03 - Técnicas em Visão Computacional":
        - modulos/03-visao/index.md
        - "Atividades":
          - "Convolução e Filtragem": modulos/03-visao/atividade1.ipynb
          - "Transformada de Hough": modulos/03-visao/atividade2.ipynb
          - "Detecção com NN": modulos/03-visao/atividade3.ipynb
          - "Pose com Aruco": modulos/03-visao/atividade4.ipynb 
      - "04 - ROS Básico":
        - modulos/04-ROS-basico/index.md
        - "Atividades":
          - "Simulador do Turtlebot": modulos/04-ROS-basico/atividades/atividade1.md
          - "Tópicos e mensagens na ROS": modulos/04-ROS-basico/atividades/atividade2.md
          - "Visualização da ROS": modulos/04-ROS-basico/atividades/atividade3.md
          - "Lista de exercícios da ROS": modulos/04-ROS-basico/atividades/atividade4.md
          - "Lista de exercícios da ROS - Parte 2": modulos/04-ROS-basico/atividades/atividade5.md
    - APS:
      - "Gravar Tela": aps/screen_record.md
      - "APS 1": aps/aps1/enunciado.md
      - "APS 2": aps/aps2/enunciado.md
      - "APS 3": aps/aps3/enunciado.md
      - "APS 4": aps/aps4/enunciado.md
    #   - revisaoPF.md
    - Provas:
      - "Simulado": provas/simulado/enunciado.md
      - "Avaliação Intermediária": provas/ai/enunciado.md
    - Projeto:
      - projeto/index.md
      - projeto/atualizacoes.md
      - "Exemplos":
        - projeto/exemplos/aruco/index.md

